"""Initial migration for summarizer

Revision ID: 3ab2009f55a3
Revises: 
Create Date: 2026-05-21 15:04:01.464436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ab2009f55a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summarized_news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=700), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('batch_date_kst', sa.String(length=32), nullable=True),
    sa.Column('scheduled_run_time_kst', sa.String(length=64), nullable=True),
    sa.Column('collected_at_kst', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.create_index('idx_summarized_news_batch_date_kst', 'summarized_news', ['batch_date_kst', 'category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_summarized_news_batch_date_kst', table_name='summarized_news')
    op.drop_table('summarized_news')
    # ### end Alembic commands ###
