"""Initial migration for mail service

Revision ID: c5b59be6e528
Revises:
Create Date: 2026-05-21 12:20:00.914922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5b59be6e528'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_send_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('to_email', sa.String(length=128), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mail_send_logs_status'), 'mail_send_logs', ['status'], unique=False)
    op.create_index(op.f('ix_mail_send_logs_subject'), 'mail_send_logs', ['subject'], unique=False)
    op.create_index(op.f('ix_mail_send_logs_to_email'), 'mail_send_logs', ['to_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mail_send_logs_to_email'), table_name='mail_send_logs')
    op.drop_index(op.f('ix_mail_send_logs_subject'), table_name='mail_send_logs')
    op.drop_index(op.f('ix_mail_send_logs_status'), table_name='mail_send_logs')
    op.drop_table('mail_send_logs')
    # ### end Alembic commands ###
