- name: EKS 파드 배포
  hosts: eks
  vars:
    eks_cluster: patrasche-news
    namespace: patrasche

  tasks:
    - name: kubeconfig 업데이트
      shell: |
        aws eks update-kubeconfig \
          --name {{ eks_cluster }} \
          --region ap-northeast-2 \
          --role-arn {{ iam_role_arn }}

    - name: 유저 서비스 파드 이미지 업데이트
      shell: |
        kubectl set image deployment/user-deployment \
          user-service={{ ecr_registry }}/patrasche-backend:{{ image_tag }} \
          -n {{ namespace }}

    - name: crawler 파드 이미지 업데이트
      shell: |
        kubectl set image deployment/fetcher-deployment \
          fetcher-service={{ ecr_registry }}/patrasche-crawler:{{ image_tag }} \
          -n {{ namespace }}

    - name: analyzer 파드 이미지 업데이트
      shell: |
        kubectl set image deployment/summarizer-deployment \
          summarizer-service={{ ecr_registry }}/patrasche-analyzer:{{ image_tag }} \
          -n {{ namespace }}

    - name: notifier 파드 이미지 업데이트
      shell: |
        kubectl set image deployment/mail-deployment \
          mail-service={{ ecr_registry }}/patrasche-notifier:{{ image_tag }} \
          -n {{ namespace }}

    - name: 배포 상태 확인
      shell: kubectl get pods -n {{ namespace }}
      register: pod_status

    - name: 파드 상태 출력
      debug:
        msg: "{{ pod_status.stdout }}"